spring:
  application:
    name: job-interview-simulator
  data:
    mongodb:
      uri: mongodb+srv://your-username:your-password@cluster0.mongodb.net/interview-simulator?retryWrites=true&w=majority
      # For local development:
      # uri: mongodb://localhost:27017/interview-simulator
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:5173
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  exposed-headers:
    - Authorization
  allow-credentials: true

logging:
  level:
    com.interviewsimulator: DEBUG
    org.springframework.security: DEBUG